from .auth import auth_bp
from .documentation import documentation_bp
from .finds_samples import finds_samples_mobile_bp
from .geodesy import geodesy_bp
from .health import health_bp
from .objects import objects_bp
from .polygons import polygons_bp
from .projects import projects_bp
from .sections import sections_bp
from .statistics import statistics_bp
from .su import su_bp
